### ISSUE TITLE
Question: Does it work without ssr for SEO, on fb and twitter ? 

### ISSUE THREAD

**Issue by rish-hub** [tizmagik/react-head#108]
Hi,
I can't have SSR in my current project as my backend is developed by someone else in PHP, 
all I have is a server serving static Build of my App built over create-react-app.

It's a blog basically with all normal functionality like reading, creating of blog post and sharing the same 
my issue is **SEO**   I am unable to preview the dynamic headers and meta data on social site like facebook and other 

please help.

**Comment by tizmagik** [comment]
react-head is a react library, so unless you're rendering react on the server side, there isn't a way to affect meta-tags server side. If possible, I would recommend rendering first server-side and output the HTML to a string that your PHP can pick up and then serve. In that scenario, it should work.
