### ISSUE TITLE
Support for renderToStaticNodeStream/rendertostaticmarkup

### ISSUE THREAD

**Issue by jamesjjk** [tizmagik/react-head#15]
@tizmagik

I'm adding an option to remove [data-reactroot=""] from the queryselector string so your library supports both static stream and static markup. Like the simplicity of what you have done!

**Comment by tizmagik** [comment]
Ah good idea, hadn’t considered that! Thanks 😁

**Comment by tizmagik** [comment]
I think I'm going to solve this by passing in a custom data attribute specific to react-head. So something like `[data-rh=""]` so that regardless of the rendering method used, react-head will know which head tags it placed and then can remove/update them on the client safely. Thoughts?

**Comment by Maarten88** [comment]
That is the same change I made, it worked well for me.

**Comment by jamesjjk** [comment]
Closing in favour of solution #14
