### ISSUE TITLE
Create common aliases (title, style, meta, link)

### ISSUE THREAD

**Issue by tizmagik** [tizmagik/react-head#2]
Would be nice to create some aliases for convenience, so that instead of doing this:

```js
import HeadTag from 'react-head';

<HeadTag tag="link" rel="canonical" content="http://jeremygayed.com/" />
```

You could do this:

```js
import { Link } from 'react-head'; // maybe HeadLink better?

<Link rel="canonical" content="http://jeremygayed.com/" />
```

The common aliases should be:

- `Title`
- `Style`
- `Meta`
- `Link`

Technically `base` and `script` are also allowed, but I can't think of a use case where you don't already know those values server-side.

**Comment by g33kidd** [comment]
Sounds like a plan! I'll give this a go! 😄

**Comment by g33kidd** [comment]
@tizmagik Is there any example on how one might use the `HeadTag` with a style?

**Comment by g33kidd** [comment]
I added some aliases over at https://github.com/g33kidd/react-head/commit/29d11a60a2ca80b8d5cb1e16ed08341374c5d653 there is a strange bug, `Cannot read property 'toLowerCase' of undefined` It's almost like the components aren't defined on initial page load, but when I uncomment the stuff in the example app, when it hot reloads the components are available again.

Really not sure what could be going on.

**Comment by tizmagik** [comment]
Thanks @g33kidd -- I pulled your branch and I don't see the error locally. Make sure you're running `npm run build:watch` in a separate terminal window so that you get the latest changes in the example app. I should document that workflow 😅

**Comment by g33kidd** [comment]
Sweet, thanks for checking! I was having an issue at first running the example app, then I did that after I realized the build files were not changing haha. Alright, I'll finish this up 😄
