### ISSUE TITLE
Duplicate Title tags

### ISSUE THREAD

**Issue by klase** [tizmagik/react-head#51]
If I render a Title head tag in my root component and then another with a different value in a child component it results in two title tags being collected on the server. Are we meant to filter collected tags manually so that there are no duplicates?

**Comment by tizmagik** [comment]
Cascading title tag support was added in https://github.com/tizmagik/react-head/pull/37 and will be published as part of an upcoming v3 -- you can play around with it now by installing the `next` tag, `npm i react-head@next`

**Comment by tizmagik** [comment]
Any feedback you have on this feature would be appreciated and super helpful right now, as we haven't yet cut an official v3 release 😁

**Comment by klase** [comment]
Ah sure will have a look at v3 then :)

**Comment by klase** [comment]
Btw, will cascading support be limited to just title tags? What about og:title, og:description etc?

**Comment by TrySound** [comment]
Only `title` and `meta` are supported currently.

**Comment by klase** [comment]
So I just tried the v3 branch, and on the server the headTags array contains only one title tag as expected. However, on the client this gets overwritten whenever the components updates client side.

Also, meta tags with the following structure doesn't cascade on server nor client:
`<Meta property="og:description" content="Some Content" />`

**Comment by tizmagik** [comment]
I think the `next` tag is an older build, I'll cut a new one with the latest on master (I think that will include the meta support).

**Comment by klase** [comment]
Great thanks @tizmagik

**Comment by tizmagik** [comment]
Just published `3.0.0-1` (against `@next` tag). Give that a spin 😁

**Comment by klase** [comment]
Yay works on the server now with the meta tags but still have the issue where it gets overwritten by the first occurring tag and title whenever client side rendering/updating kicks in. 

I also get an error when navigating away from any page with nested titles or tags in its component tree:
`this.headTags.removeClientTag is not a function
    at HeadTag.componentWillUnmount`

**Comment by tizmagik** [comment]
Thanks for the bug report @klase ! -- cc @TrySound

**Comment by TrySound** [comment]
@klase Do you have HeadProvider in your tree in client?

**Comment by praxxis** [comment]
I'm seeing this too on `3.0.0-1`, client side only, with a `HeadProvider`. A `title` tag is defined in our index.html, and it's not being overwritten by the `Title` `react-head` tag (a second `title` tag is inserted in `head` by `react-head`, but it's ignored by the browser). `react-helmet` doesn't have the same issue, it seems to replace the existing title.

**Comment by klase** [comment]
ahh nope 🤦‍♂️ thanks @TrySound. Maybe it can be added to the Client Setup section of the readme to make it clearer. 

Unrelated: In the readme you're using renderToString to render the headTags array. Any reason why you're not using renderToStaticMarkup instead to avoid having data-reactroot attributes on all the tags?

**Comment by TrySound** [comment]
@praxxis We are doing "rehydration" only for tags with `data-rh` attributes. Removing another stuff won't affect SSR and may break something. It's probably better to not have `title` tag in your source html.

**Comment by TrySound** [comment]
@klase Nope, could you open an issue about that?

**Comment by klase** [comment]
Closing this as 3.0.0-1 resolved my initial issue.
