### ISSUE TITLE
Suggestion: use renderToStaticMarkup instead of renderToString

### ISSUE THREAD

**Issue by klase** [tizmagik/react-head#54]
In the readme renderString is used to render the headTags array. This adds a data-reactroot attribute to every element. Since only data-rh is used to "hydrate" anyway, renderToStaticMarkup might be a better choice to save a few bytes and get cleaner markup.

**Comment by klase** [comment]
Thanks @tizmagik could you publish a new @next release to npm so I can test the last few updates?

**Comment by TrySound** [comment]
Or we can land stable release and fix issues if they come.

**Comment by tizmagik** [comment]
This is now fixed with the [latest v3.0.0 release](https://github.com/tizmagik/react-head/releases/tag/v3.0.0). Please feel free to open a new issue if there's still any problems.
