### ISSUE TITLE
Invariant failed in HeadTags

### ISSUE THREAD

**Issue by casertap** [tizmagik/react-head#62]
I following the example to try to run this library on dev env and and prod env with ssr.
dev env is working fine but prod env with ssr is crashing with:
```

(node:25652) UnhandledPromiseRejectionWarning: Error: Invariant failed
    at index (/home/pc/Documents/funspace/babysearch/isomorphic-react-redux-saga-ssr/build/Routes.js:12781:11)
    at Object.children (/home/pc/Documents/funspace/babysearch/isomorphic-react-redux-saga-ssr/build/Routes.js:2365:110)
    at a.render (/home/pc/Documents/funspace/babysearch/isomorphic-react-redux-saga-ssr/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:400)
    at a.read (/home/pc/Documents/funspace/babysearch/isomorphic-react-redux-saga-ssr/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:288)
    at Object.renderToString (/home/pc/Documents/funspace/babysearch/isomorphic-react-redux-saga-ssr/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:6)
    at loadBranchData.then._data (/home/pc/Documents/funspace/babysearch/isomorphic-react-redux-saga-ssr/lib/server/ssr.js:116:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:25652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
I took a screenshot to show you what the line `/isomorphic-react-redux-saga-ssr/build/Routes.js:2365` correspond to:

![screenshot from 2018-09-10 15-00-59](https://user-images.githubusercontent.com/284394/45277682-b07cbd00-b50c-11e8-88a6-fc31a887a9fe.png)

My SSR setup is pretty straightforward with:

```
  loadBranchData(location, routes).then(_data => {
    const context = {
      splitPoints: [],
    };
    const headTags = [];
    const rootComponent = PROD ? (
      <IntlProvider locale={locale} messages={messages[locale]}>
        <Provider store={store}>
          <HeadProvider headTags={headTags}>
            <StaticRouter location={location} context={context}>
              <Layout />
            </StaticRouter>
          </HeadProvider>
        </Provider>
      </IntlProvider>
    ) : null;
    const markup = ReactDOMServer.renderToString(rootComponent);
    const state = store.getState();
    const html = ReactDOMServer.renderToStaticMarkup(
      <Html
        PROD={PROD}
        assets={assets}
        markup={markup}
        state={state}
        splitPoints={context.splitPoints}
        localeData={localeData[locale]}
      />
    );
    res.send(doctype + html);
```

it is crashing on the line ` const markup = ReactDOMServer.renderToString(rootComponent);`

My client is having this code:
```
const rootEl = document.getElementById("root");
const renderApp = localeData => {
  hydrate(
    <IntlProvider locale={appLocale} messages={localeData}>
      <Provider store={store}>
        <HeadProvider>
          <AppContainer history={history} />
        </HeadProvider>
      </Provider>
    </IntlProvider>,
    rootEl
  );
};
```

and down the AppContainer component and many other child components I render some Title and Meta
```
const DirectoryLayout = _props => (
  <div>
    <Title>Browse Directory</Title>
    <Meta name="description" content="Some directory" />
    <Meta property="og:title" content="Directory" />
    <Meta property="og:image" content="path/to/image.jpg" />
    <AlphabetLinks />
    <AlphabetDirectory />
  </div>
);
```

Can you please help solving this issue?

**Comment by casertap** [comment]
This is the React tree on my dev env:

![screenshot from 2018-09-10 15-43-40](https://user-images.githubusercontent.com/284394/45278423-5c73d780-b510-11e8-9c2b-86643edec5a8.png)

**Comment by casertap** [comment]
For some reasons the React Context did not make it to the HeadTag component, making this line fail:
https://github.com/tizmagik/react-head/blob/b294fa74b4bdc01ae10a23e933da649467eba869/src/HeadTag.js#L30

Now I am using the redux (provider) with the connect method (consumer) on server side without any issue.

**Comment by TrySound** [comment]
Could you try to wrap all other providers with HeadProvider. There can be a conflict between old and new context apis.

**Comment by casertap** [comment]
I am also trying react-helmet-async and I also got some weird errors. 

I am doing something a little unconventional on the server side and this might be the issue. 
I have an `universal` folder a `client` folder and a `server` folder.
On the server side I using babel alone to transpile the few js files in the `server` folder but then I use webpack to build the `universal` bundle (on the server side).
The entry point it a top level component called Routes.

my `server.js` file just require the build component like that:
```
  const Layout = require("../../build/Routes.js").default
````
And then I use this top level component like this:
```
 const rootComponent = PROD ? (
      <IntlProvider locale={locale} messages={messages[locale]}>
        <Provider store={store}>
          <HeadProvider headTags={headTags}>
            <StaticRouter location={location} context={context}>
              <Layout />
            </StaticRouter>
          </HeadProvider>
        </Provider>
      </IntlProvider>
    ) : null;
```
My transpiled `server` will still use the `node_modules` folder during runtime.
While my `Routes` bundle will include it own node_modules js file within the bundle.

Can you tell me if you think this is an issue?
Because from what I understood the React.Context should be the same (it is kind of statefull).

**Comment by casertap** [comment]
@TrySound 
I tried to wrap my HeadTags with a HeadProvider within the `universal` components but I still ge the same error

**Comment by TrySound** [comment]
This error looks like you have two instances of head context. Make sure you use one instance in server side. Try to put `console.log` in react-head/dist/index.cjs.js and react-head/dist/index.esm.js and then run your app.

**Comment by oyeanuj** [comment]
@casertap What solution did you end up with here?

**Comment by TrySound** [comment]
@oyeanuj Add HeadProvider in the root of the tree like said in docs.
