### ISSUE TITLE
does not support ie9?

### ISSUE THREAD

**Issue by Symboler** [tizmagik/react-head#68]
![image](https://user-images.githubusercontent.com/33592051/46252216-51b9bc00-c498-11e8-9f9f-05043c6d3c7f.png)

**Comment by TrySound** [comment]
No. IE9 will never be supported since it's dead browser.
https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

**Comment by Symboler** [comment]
thanks!
