### ISSUE TITLE
Proposal: headTagsToElement(headTags)

### ISSUE THREAD

**Issue by umidbekkarimov** [tizmagik/react-head#70]
Currently  `renderToString` of `headTags` with parent elements gives `Warning: Each child in an array or iterator should have a unique "key" prop.`.

```javascript 
const headHtml = renderToString(
  <head>
     {sheet.getStyleElement()}

     {headTags}
  </head>
)
```

So as a workaround I'm using `React.createElement` + `React.Fragment`.
```javascript
const headHtml = renderToString(
  <head>
     {sheet.getStyleElement()}

     {React.createElement(React.Fragment, {}, ...headTags)}
  </head>
)
```

It would be good if `react-head` had it's own utility to handle this situation, e.g:
```javascript
export const headTagsToElement = headTags =>
  React.createElement(React.Fragment, {}, ...headTags);
```

I would glad to add PR after merge of #69.

**Comment by TrySound** [comment]
I'd say `React.createElement(React.Fragment, {}, ...headTags)` is already utility which works great. Thanks for the tip. I would be glad to see PR to readme instead.
