### ISSUE TITLE
Element.remove() not supported in IE

### ISSUE THREAD

**Issue by alekrist** [tizmagik/react-head#72]
We get a JS exception when using the package in IE11 in this line (index.esm.js):
![2018-11-07 11_06_52-index esm js](https://user-images.githubusercontent.com/5364604/48124741-60f10e00-e27d-11e8-8275-aa1993143f63.png)

According to [this page](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) , the remove() method is not supported at all in IE.
We currently use the polyfill mentioned in the same link as a workaround, but it would be much better if the package already handles that.

**Comment by TrySound** [comment]
@alekrist PR welcome

**Comment by alekrist** [comment]
@TrySound here you go:
#73

**Comment by alekrist** [comment]
Fixed in v3.0.2
