### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by dangodev** [tizmagik/react-head#75]
Thanks for providing such a great package! Was running into react-helmet’s deprecated lifecycle API and was happy to find this solution.

I’m using it in a TypeScript environment, which (obviously) doesn’t seem to understand Flow, and needs definitions. [The @types repo](https://github.com/DefinitelyTyped/DefinitelyTyped) recommends shipping these TS definitions in the original package rather than in a separate `@types/react-head` repo (workaround for when the original package is missing definitions).

Would it be possible to ship the following definition file as `dist/index.d.ts` to npm? I’m using the following locally and this seems to make TypeScript happy. Happy to submit a PR if that’s helpful. Feedback welcome.

```ts
declare module 'react-head' {
  export const HeadProvider: React.ComponentClass<{
    headTags?: React.ReactChildren;
  }>;

  export const Link: React.FunctionComponent<React.HTMLProps<HTMLLinkElement>>;

  export const Meta: React.FunctionComponent<React.HTMLProps<HTMLMetaElement>>;

  export const Style: React.FunctionComponent<React.HTMLProps<HTMLStyleElement>>;

  export const Title: React.FunctionComponent<React.HTMLProps<HTMLTitleElement>>;
}
```

**Comment by TrySound** [comment]
Sure, PR welcome. However you missed something in HeadProvider
https://github.com/tizmagik/react-head/blob/master/src/index.js.flow

**Comment by dangodev** [comment]
`children`? I think TypeScript shouldn’t need that because I’m extending `React.ComponentClass`—it inherits `children` from that (along with other React APIs like synthetic events, etc).

**Comment by TrySound** [comment]
AFAIK there is generic `ComponentType` similar to flow. Could you use it instead?
